spring.application.name=Spring-MVC
#spring.mvc.view.prefix=/view/
#spring.mvc.view.suffix=.jsp
server.port=8081
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html